import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>Tuna Daştan Mimarlık</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
        <meta name="msapplication-TileColor" content="#da532c"/>
        <meta name="theme-color" content="#ffffff"/>
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
